server:
  port: 9090

spring:
  h2:
    console:
      enabled: true  # H2 웹 콘솔을 사용하겠다는 의미
      path: /h2-console  # 콘솔의 경로

  datasource:
    driver-class-name: org.h2.Driver  #h2 드라이버 설정
    url: jdbc:h2:mem:testdb  #접속 URL
    username: sa   # 사용자 이름 (로그인 시 사용)
    password:   # 사용자 암호 (로그인 시 사용)